name: Issue to PR (Gemini)

on:
  issues:
    types: [labeled]

jobs:
  from-issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'codex'   # ラベル 'codex' が付いたIssueのみ実行
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set git user (bot)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install JS deps
        run: npm ci

      - name: Generate patch via Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY:  ${{ github.event.issue.body }}
          ISSUE_NUM:   ${{ github.event.issue.number }}
        run: |
          BRANCH="gemini/issue-${ISSUE_NUM}"
          git switch -c "$BRANCH"

          node .github/scripts/make-patch.js "$ISSUE_TITLE" "$ISSUE_BODY" > ai.patch

          if [ ! -s ai.patch ]; then
            echo "No patch generated."
            exit 0
          fi

          # パッチ適用（失敗時はログ出して終了）
          set -e
          echo "---- PATCH ----"
          head -n 200 ai.patch || true
          echo "---------------"

          git apply -p0 --index ai.patch

          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Fix: #${ISSUE_NUM} – ${ISSUE_TITLE}"
            git push -u origin "$BRANCH"
          else
            echo "No changes after apply."
            exit 0
          fi

      - name: Create Pull Request
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUM: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          gh pr create \
            --title "Fix: #${ISSUE_NUM} – ${ISSUE_TITLE}" \
            --body "Automated fix generated by Gemini API." \
            --head "gemini/issue-${ISSUE_NUM}" \
            --base "main"
